### ISSUE TITLE
Blank page shown for graphical view-Home page

### ISSUE THREAD

**Issue by LakshmiTejaP** [haigopi/functional-automation#144]
In the following cases blank page is visible when clicked on graphical view:

1)Sunburst->Shipments->Freight Charges->Currency->Graphical view
2)Sunburst->Shipments->Packing Items->Active Package->Graphical view
3)Sunburst->Shipments->Shipments->Manifest Flag->Graphical view
4)Sunburst->Shipments->Shipments->Shipment Type->Graphical view
5)Sunburst->Shipments->International->Country of Origin->Graphical view

The following page is displayed:

![2020-10-05 (2)](https://user-images.githubusercontent.com/67819243/95059741-ed7d0300-0716-11eb-9729-02f10be5e360.png)

[In remaining all cases it is working fine.]

**Comment by lpriyankapodila** [comment]
closing this issue to cline up this repo
issue is fixed
