### ISSUE TITLE
Page loading for long time and showing nothing-Location Cluster

### ISSUE THREAD

**Issue by LakshmiTejaP** [haigopi/functional-automation#145]
Go to Sunburst->Shipments->Location->Location Address.

Page keeps loading for long time and nothing is displayed:
![2020-10-05 (5)](https://user-images.githubusercontent.com/67819243/95062204-4e5a0a80-071a-11eb-98b7-035433f4612b.png)

**Comment by lpriyankapodila** [comment]
closing this issue to cline up this repo
issue is fixed
