### ISSUE TITLE
Verify in Datastudio >International cluster -Internal View - Foreign keys

### ISSUE THREAD

**Issue by lpriyankapodila** [haigopi/functional-automation#16]
**Test case Scenario**:Verify in Datastudio >International cluster -Internal View - Foreign keys
**Prerequisite**:
            1.Access to chrome driver
            2. Make sure Login Page is working.
 Test Case | Expected Result | Actual Result
-- | -- | --
**Test case Id**:|testVerifyInternationalDocumentsClick()
| |
Login to A4Data |  Login to URL:https://a4data-qe.netlify.app/dashboard/ |  Login to URL:https://a4data-qe.netlify.app/dashboard/ 
|  | 
Click on data studio - Smart View is displayed | After Login to A4Data Click on DataStudio Button in Header .IN Smart view DB(Data Studio ) will Expand | After Login to A4Data Clicked on DataStudio Button in Header .IN Smart view DB(Data Studio ) Is(should be open clPanel tree) Expanded
| |
Select Smart view  Data Studio| select smart view and make sure it is Displaying Data Studio Tree(should be open clPanel tree)And make sure it expands and collapse| selected smart view . Data Studio Tree(should be open clPanel tree)is Displayed .Smart View expands is displaying Data Studio Tree(should be open clPanel tree)DataStudio .When Smart View Collapse Data Studio Tree is collapsed
| |
Internal View in DataStudio|For Internal View Select Subject Shipments in Data Studio Tree.IN Subject Shipments Select AnyCluster to Display internal view|Clicked on Subject Shipments Went in to International Cluster internal View is Displayed 
| |
International cluster -Internal View - Foreign keys|International Cluster go in to Foreign  key Elements And Click On Then And Verify |Went into international Cluster Clicked on Handling Unit And Shipping number Foreign  key Elements  .
| |

**Comment by hemadata24** [comment]
Verify under Data studio select International cluster and verify foreign key in Internal view.
