### ISSUE TITLE
Verify Reset button clear the search bubble by selecting from a query from Query History search

### ISSUE THREAD

**Issue by hemadata24** [haigopi/functional-automation#20]
**Test case Scenario**:Verify Reset Button SearchBar

**Prerequisite**:
                  1.Access to chrome driver
                  2. Make sure Login Page is working.

               
 **Test Case** | **Expected Result** | **Actual Result**
-- | -- | --
--|
Login to A4Data |  Login to URL:https://a4data-qe.netlify.app/dashboard/ |  Login to URL:https://a4data-qe.netlify.app/dashboard/ 
|  | 
Select a cluster and copy a Query from Query History Search | Query is shown on the search bar  |   Query is shown on the search bar
|  | 
Clicking on Reset button and effect on Search Bar | Search Bar should be empty  |   Search Bar should be empty
|  | 
**Test(Pass/Fail)**:  | **Pass**|**Pass**

**Comment by Harithamadi** [comment]
ID is missing for Copy Query button testing is blocked, we can't automate. selenium detecting that component using below text svg.MuiSvgIcon-root.mr-2 > we need ID to pass this testcase.
