### ISSUE TITLE
Verify document cluster with manual queries

### ISSUE THREAD

**Issue by hemadata24** [haigopi/functional-automation#55]

**Comment by LakshmiTejaP** [comment]
| Test Case | Expected Result | Actual Result |
-- | -- | -- | -- |   
|  Login to A4Data | Login to URL:https://a4data-qe.netlify.app/dashboard/ | Login to URL:https://a4data-qe.netlify.app/dashboard/  | 
|  Click Help Button | Sunburst shown with tabs (info) | Sunburst Opens and Current History, Private, Public Query Tabs shown  |  
|  Click Private Queries Button | All Private Queries Shown | All Private Queries Shown |
| Click Private Queries Button | All Private Queries Shown | All Private Queries Shown |
| Click Execute NLP Query Button(hover element) for any private query | Tabular view of the private query shown | Scroll down and Tabular view of the specific query is displayed |

**Comment by LakshmiTejaP** [comment]
| Test Case | Expected Result | Actual Result |
| --- | --- | --- |   
|  Login to A4Data | Login to URL:https://a4data-qe.netlify.app/dashboard/ | Login to URL:https://a4data-qe.netlify.app/dashboard/  | 
|  Click Help Button | Sunburst shown with tabs (info) | Sunburst Opens and Current History, Private, Public Query Tabs shown  |  
|  Click Private Queries Button | All Private Queries Shown | All Private Queries Shown |
| Click Private Queries Button | All Private Queries Shown | All Private Queries Shown |
| Click Execute NLP Query Button(hover element) for any private query | Tabular view of the private query shown | Scroll down and Tabular view of the specific query is displayed |

**Comment by LakshmiTejaP** [comment]
| Command | Description |
| --- | --- |
| git status | List all new or modified files |
| git diff | Show file differences that haven't been staged |

**Comment by LakshmiTejaP** [comment]
Test Case | Expected Result | Actual Result
-- | -- | --
-- |   |  
Login to A4Data | Login to URL:https://a4data-qe.netlify.app/dashboard/ | Login to URL:https://a4data-qe.netlify.app/dashboard/
  |   |  
Click Help Button | Sunburst shown with tabs (info) | Sunburst Opens and Current History, Private, Public Query Tabs shown
  |   |  
Click Private Queries Button | All Private Queries Shown | All Private Queries Shown

**Comment by LakshmiTejaP** [comment]
Test Case | Expected Result | Actual Result
-- | -- | --
-- |   |  
Login to A4Data | Login to URL:https://a4data-qe.netlify.app/dashboard/ | Login to URL:https://a4data-qe.netlify.app/dashboard/
  |   |  
Click Help Button | Sunburst shown with tabs (info) | Sunburst Opens and Current History, Private, Public Query Tabs shown
  |   |  
Click Private Queries Button | All Private Queries Shown | All Private Queries Shown 
  |   |
Click Execute NLP Query Button(hover element) for any private query | Tabular view of the private query shown | Scroll down and Tabular view of the specific query is displayed
