### ISSUE TITLE
 Donut Graph is not working and It is displaying Pie graph instead of Donut Graph

### ISSUE THREAD

**Issue by gollaprasanna01** [haigopi/functional-automation#78]
Throw Sunburst
1.click on ->Help button->shipments->Document URL ->Document Provider ->Help button ->Other Graphical View
In Other Graphical View 
1.select the Donut Graph 
2. click on Show button
3.It displaying Pie Graph not Donut Graph Model

![Manual testing of Donut Graph](https://user-images.githubusercontent.com/67251080/88722995-bde5c500-d0ed-11ea-83e6-63a535708daf.PNG)

**Comment by hemadata24** [comment]
This is not an issue. Donut graph is displayed correctly.
