### ISSUE TITLE
Homepage - Verify Location Cluster Queries #62

### ISSUE THREAD

**Issue by Saraswathi-Kakollu** [haigopi/functional-automation#79]
Tabular view is not displaying while testing manually,

Under Shipments / Location / Location Address.

**Comment by hemadata24** [comment]
<img width="833" alt="location_address" src="https://user-images.githubusercontent.com/65037794/88994179-61c99f00-d2ad-11ea-90da-5682e080a98a.PNG">

**Comment by hemadata24** [comment]
Will update once data is loaded for locations.
